# Generated by Django 3.1.14 on 2022-02-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
            ],
            options={
                'db_table': 'DEPARTAMENTO',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='places.department', verbose_name='department')),
            ],
            options={
                'db_table': 'PROVINCIA',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='places.province', verbose_name='province')),
            ],
            options={
                'db_table': 'DISTRITO',
            },
        ),
    ]
