# Generated by Django 3.1.14 on 2022-03-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placescope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, null=True, verbose_name='source')),
                ('utm', models.IntegerField(verbose_name='utm')),
                ('gis_service', models.CharField(max_length=255, verbose_name='gis service')),
                ('ubigeo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.district', verbose_name='ubigeo')),
            ],
            options={
                'db_table': 'UBICACION_RECURSOS',
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.CharField(max_length=20)),
                ('x_max', models.CharField(max_length=20)),
                ('y_min', models.CharField(max_length=20)),
                ('y_max', models.CharField(max_length=20)),
                ('x', models.CharField(max_length=20)),
                ('y', models.CharField(max_length=20)),
                ('id_dist', models.IntegerField(null=True)),
                ('ubigeo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.district', verbose_name='ubigeo')),
            ],
            options={
                'db_table': 'UBICACION_EXTENDIDO',
            },
        ),
    ]
