# Generated by Django 3.1.14 on 2022-03-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_extension_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='ubigeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='places.district', verbose_name='ubigeo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ubigeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='places.district', verbose_name='ubigeo'),
        ),
    ]
