# Generated by Django 3.2.15 on 2022-09-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20220331_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='zone',
            field=models.CharField(default=18, max_length=2, verbose_name='zone'),
            preserve_default=False,
        ),
    ]
