# Generated by Django 3.2.16 on 2022-11-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_district_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'district', 'verbose_name_plural': 'districts'},
        ),
        migrations.AlterModelOptions(
            name='extension',
            options={'verbose_name': 'extension', 'verbose_name_plural': 'extensions'},
        ),
        migrations.AlterModelOptions(
            name='placescope',
            options={'verbose_name': 'place scope', 'verbose_name_plural': 'place scopes'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'province', 'verbose_name_plural': 'provinces'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
    ]
