# Generated by Django 3.2.19 on 2024-06-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20221127_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='municipal_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
