# Generated by Django 3.2.19 on 2024-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_district_municipal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='sec_ejec',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
