# Generated by Django 3.2.19 on 2024-09-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_district_sec_ejec'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
