# Generated by Django 3.2.19 on 2024-09-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_district_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
