# Generated by Django 3.2.19 on 2023-10-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandInspectionUpload',
            fields=[
                ('cod_carga', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Land Inspection',
                'verbose_name_plural': 'LandS Inspection',
                'db_table': 'TB_INSPECCION_PREDIAL',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('cod_ubicacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cod_tip_via', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_via', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_via', models.CharField(blank=True, max_length=255, null=True)),
                ('num_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_tipo_uu', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_uu', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_uu', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('km', models.CharField(blank=True, max_length=255, null=True)),
                ('x', models.FloatField(blank=True, db_column='coor_x', null=True)),
                ('y', models.FloatField(blank=True, db_column='coor_y', null=True)),
                ('lot_urb', models.CharField(blank=True, max_length=255, null=True)),
                ('num_mun', models.CharField(blank=True, max_length=255, null=True)),
                ('mzn_urb', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('obs_ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location',
                'db_table': 'TB_UBICACION',
            },
        ),
        migrations.CreateModel(
            name='OwnerShipType',
            fields=[
                ('cod_tipo_tit', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_tit', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'OwnerShip Type',
                'verbose_name_plural': 'OwnerShip Type',
                'db_table': 'TB_TIPO_TITULARIDAD',
            },
        ),
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('cod_tipo_foto', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_foto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Photo Type',
                'verbose_name_plural': 'Photo Type',
                'db_table': 'TB_TIPO_FOTO',
            },
        ),
        migrations.CreateModel(
            name='TicketSendStation',
            fields=[
                ('cod_est_envio_ticket', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('desc_est_envio_ticket', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ticket SendStation',
                'verbose_name_plural': 'Ticket SendStation',
                'db_table': 'TB_EST_ENVIO_TICKET',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('cod_tipo_ticket', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desc_tipo_ticket', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
                'db_table': 'TB_TIPO_TICKET',
            },
        ),
        migrations.CreateModel(
            name='TicketWorkStation',
            fields=[
                ('cod_est_trabajo_ticket', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('desc_est_trabajo_ticket', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ticket WorkStation',
                'verbose_name_plural': 'Ticket WorkStation',
                'db_table': 'TB_EST_TRABAJO_TICKET',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('cod_ticket', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('obs_ticket_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('fec_inicio_trabajo', models.DateTimeField(blank=True, null=True)),
                ('fec_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fec_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('obs_ticket_gabinete', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_carga', models.ForeignKey(blank=True, db_column='cod_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_inspections.landinspectionupload')),
                ('cod_est_envio_ticket', models.ForeignKey(blank=True, db_column='cod_est_envio_ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_inspections.ticketsendstation')),
                ('cod_est_trabajo_ticket', models.ForeignKey(blank=True, db_column='cod_est_trabajo_ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_inspections.ticketworkstation')),
                ('cod_tipo_ticket', models.ForeignKey(blank=True, db_column='cod_tipo_ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_inspections.tickettype')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Ticket',
                'db_table': 'TB_TICKET',
            },
        ),
        migrations.CreateModel(
            name='RecordOwnerShip',
            fields=[
                ('cod_tit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cod_tipo_tit', models.ForeignKey(blank=True, db_column='cod_tipo_tit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_inspections.ownershiptype')),
                ('cod_ubicacion', models.ForeignKey(db_column='cod_ubicacion', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.location')),
            ],
            options={
                'verbose_name': 'OwnerShip',
                'verbose_name_plural': 'OwnerShip',
                'db_table': 'TB_REGISTRO_TITULARIDAD',
            },
        ),
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('cod_foto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='land_inspections')),
                ('cod_tipo_foto', models.ForeignKey(db_column='cod_tipo_foto', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.phototype')),
                ('cod_ubicacion', models.ForeignKey(db_column='cod_ubicacion', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.location')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photo',
                'db_table': 'TB_FOTOS',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='cod_ticket',
            field=models.ForeignKey(db_column='cod_ticket', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.ticket'),
        ),
    ]
