# Generated by Django 3.2.19 on 2023-10-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0002_facilitytype_landcharacteristic_landfacility_landsupply_supplytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandInspection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubigeo', models.CharField(max_length=6)),
                ('cod_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_pre', models.CharField(blank=True, max_length=50, null=True)),
                ('piso', models.CharField(blank=True, max_length=100, null=True)),
                ('num_sumi_agua', models.CharField(blank=True, max_length=100, null=True)),
                ('num_sumi_luz', models.CharField(blank=True, max_length=100, null=True)),
                ('uso_especifico', models.CharField(blank=True, max_length=100, null=True)),
                ('interior', models.CharField(blank=True, max_length=100, null=True)),
                ('obs_predio', models.CharField(blank=True, max_length=100, null=True)),
                ('num_dpto', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_uso', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('num_sumi_gas', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Land Inspection',
                'verbose_name_plural': 'Lands Inspection',
                'db_table': 'TB_PREDIO_INSPEC',
            },
        ),
        migrations.CreateModel(
            name='LandInspectionType',
            fields=[
                ('cod_tipo_predio', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_predio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Facility Type',
                'verbose_name_plural': 'Facility Types',
                'db_table': 'TB_TIP_PREDIO_INSPEC',
            },
        ),
        migrations.CreateModel(
            name='LandOwnerInspection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_contr', models.CharField(max_length=50)),
                ('tip_doc', models.CharField(blank=True, max_length=2, null=True)),
                ('doc_iden', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('ap_mat', models.CharField(blank=True, max_length=100, null=True)),
                ('ap_pat', models.CharField(blank=True, max_length=150, null=True)),
                ('cond_contr', models.CharField(blank=True, max_length=150, null=True)),
                ('contribuyente', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('conyuge', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Land Owner Inspection',
                'verbose_name_plural': 'Land Owner Inspection',
                'db_table': 'TB_CONTRIBUYENTE_INSPEC',
            },
        ),
        migrations.AlterField(
            model_name='landcharacteristic',
            name='cod_tit',
            field=models.OneToOneField(db_column='cod_tit', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.recordownership'),
        ),
        migrations.AlterField(
            model_name='landsupply',
            name='cod_tit',
            field=models.OneToOneField(db_column='cod_tit', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.recordownership'),
        ),
        migrations.CreateModel(
            name='LandOwnerDetailInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo', models.CharField(max_length=6)),
                ('doc_iden', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_pre', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_contr_inspec', models.ForeignKey(db_column='cod_contr_inspec', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.landownerinspection')),
                ('cod_pred_inspec', models.ForeignKey(db_column='cod_pred_inspec', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.landinspection')),
                ('cod_tit', models.ForeignKey(db_column='cod_tit', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.recordownership')),
            ],
            options={
                'verbose_name': 'Land Inspection',
                'verbose_name_plural': 'Lands Inspection',
                'db_table': 'TB_PREDIO_CONTRIBUYENTE_INSPEC',
            },
        ),
        migrations.AddField(
            model_name='landinspection',
            name='cod_tipo_predio',
            field=models.ForeignKey(blank=True, db_column='cod_tipo_predio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_inspections.landinspectiontype'),
        ),
        migrations.AddField(
            model_name='landinspection',
            name='cod_tit',
            field=models.OneToOneField(db_column='cod_tit', on_delete=django.db.models.deletion.CASCADE, to='land_inspections.recordownership'),
        ),
    ]
