# Generated by Django 3.2.19 on 2024-08-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_auto_20240801_0934'),
        ('land_inspections', '0002_alter_location_cod_tipo_uu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landinspection',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='landinspection',
            name='uso_especifico',
        ),
        migrations.AddField(
            model_name='landinspection',
            name='codigo_clase_uso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landinspection',
            name='codigo_sub_clase_uso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landcharacteristic',
            name='estado_conserva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landcharacteristic',
            name='material_pred',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='landfacility',
            name='estado_conserva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landinspection',
            name='cod_tipo_predio',
            field=models.ForeignKey(blank=True, db_column='cod_tipo_predio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.masterpropertytype'),
        ),
    ]
