# Generated by Django 3.2.19 on 2023-11-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0003_auto_20231030_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landinspectiontype',
            options={'verbose_name': 'Facility Type', 'verbose_name_plural': 'Land Inspection Types'},
        ),
        migrations.AlterModelOptions(
            name='landinspectionupload',
            options={'verbose_name': 'Land Inspection', 'verbose_name_plural': 'Lands Inspection Upload'},
        ),
        migrations.AlterModelOptions(
            name='landownerdetailinspection',
            options={'verbose_name': 'Land Inspection', 'verbose_name_plural': 'Lands Owner Detail Inspection'},
        ),
        migrations.AlterModelOptions(
            name='supplytype',
            options={'verbose_name': 'Facility Type', 'verbose_name_plural': 'Supply Types'},
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'pendiente'), (6, 'resuelto'), (98, 'observado')], db_column='estado', default=0, null=True),
        ),
        migrations.AddField(
            model_name='recordownership',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'pendiente'), (6, 'resuelto'), (98, 'observado')], db_column='estado', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='landcharacteristic',
            name='cod_tit',
            field=models.OneToOneField(db_column='cod_tit', on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='land_inspections.recordownership'),
        ),
        migrations.AlterField(
            model_name='landfacility',
            name='cod_tit',
            field=models.ForeignKey(db_column='cod_tit', on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='land_inspections.recordownership'),
        ),
        migrations.AlterField(
            model_name='landinspection',
            name='cod_tit',
            field=models.OneToOneField(db_column='cod_tit', on_delete=django.db.models.deletion.CASCADE, related_name='predio', to='land_inspections.recordownership'),
        ),
        migrations.AlterField(
            model_name='landsupply',
            name='cod_tit',
            field=models.OneToOneField(db_column='cod_tit', on_delete=django.db.models.deletion.CASCADE, related_name='suministro', to='land_inspections.recordownership'),
        ),
        migrations.AlterField(
            model_name='locationphoto',
            name='cod_ubicacion',
            field=models.ForeignKey(db_column='cod_ubicacion', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='land_inspections.location'),
        ),
        migrations.AlterField(
            model_name='recordownership',
            name='cod_ubicacion',
            field=models.ForeignKey(db_column='cod_ubicacion', on_delete=django.db.models.deletion.CASCADE, related_name='registros_titularidad', to='land_inspections.location'),
        ),
    ]
