# Generated by Django 3.2.19 on 2023-11-09 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land_inspections', '0003_auto_20231030_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinspectionupload',
            name='user',
            field=models.ForeignKey(blank=True, db_column='cod_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
