# Generated by Django 3.2.19 on 2023-11-08 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0054_merge_0047_auto_20230829_1144_0053_auto_20231006_0952'),
        ('land_inspections', '0004_auto_20231107_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='landsupply',
            name='cod_contr',
            field=models.ForeignKey(blank=True, db_column='cod_contr', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suministro', to='lands.landowner'),
        ),
        migrations.AlterField(
            model_name='landinspection',
            name='cod_tit',
            field=models.OneToOneField(db_column='cod_tit', on_delete=django.db.models.deletion.CASCADE, related_name='predio_inspeccion', to='land_inspections.recordownership'),
        ),
        migrations.AlterField(
            model_name='landownerdetailinspection',
            name='cod_contr_inspec',
            field=models.ForeignKey(db_column='cod_contr_inspec', on_delete=django.db.models.deletion.CASCADE, related_name='contribuyentes', to='land_inspections.landownerinspection'),
        ),
        migrations.AlterField(
            model_name='landownerdetailinspection',
            name='cod_pred_inspec',
            field=models.ForeignKey(db_column='cod_pred_inspec', on_delete=django.db.models.deletion.CASCADE, related_name='predio_contribuyente', to='land_inspections.landinspection'),
        ),
    ]
