# Generated by Django 3.2.19 on 2023-11-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0004_landinspectionupload_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsendstation',
            options={'verbose_name': 'Ticket Send state', 'verbose_name_plural': 'Ticket Send state'},
        ),
        migrations.AlterModelOptions(
            name='ticketworkstation',
            options={'verbose_name': 'Ticket Work state', 'verbose_name_plural': 'Ticket Work state'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='cod_carga',
        ),
    ]
