# Generated by Django 3.2.19 on 2024-08-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0004_auto_20240801_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cod_ubicacion',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
