# Generated by Django 3.2.19 on 2023-11-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0005_auto_20231108_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='file_obs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='cod_ticket',
            field=models.ForeignKey(db_column='cod_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='land_inspections.ticket'),
        ),
    ]
