# Generated by Django 3.2.19 on 2023-11-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0005_auto_20231114_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinspectionupload',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landinspectionupload',
            name='cod_carga',
            field=models.CharField(max_length=10),
        ),
    ]
