# Generated by Django 3.2.19 on 2024-09-05 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_rename_masterpropertytype_mastertipopredio'),
        ('land_inspections', '0006_auto_20240904_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinspection',
            name='codigo_clase_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.masterclaseuso'),
        ),
        migrations.AlterField(
            model_name='landinspection',
            name='codigo_sub_clase_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.mastersubclaseuso'),
        ),
        migrations.AlterField(
            model_name='landinspection',
            name='codigo_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.mastertipousopredio'),
        ),
    ]
