# Generated by Django 3.2.19 on 2023-11-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0006_auto_20231114_1527'),
        ('land_inspections', '0007_ticket_inspection_upload'),
    ]

    operations = [
    ]
