# Generated by Django 3.2.19 on 2023-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0008_merge_20231115_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
