# Generated by Django 3.2.19 on 2023-11-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0009_location_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='landownerinspection',
            name='cod_tit',
            field=models.ForeignKey(db_column='cod_tit', default=1, on_delete=django.db.models.deletion.CASCADE, to='land_inspections.recordownership'),
            preserve_default=False,
        ),
    ]
