# Generated by Django 3.2.19 on 2024-09-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_mastertipoobracomplementaria'),
        ('land_inspections', '0010_landfacility_piso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landfacility',
            name='cod_tipo_inst',
        ),
        migrations.RemoveField(
            model_name='landfacility',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='landfacility',
            name='piso',
        ),
        migrations.AddField(
            model_name='landfacility',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='landfacility',
            name='categoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='landfacility',
            name='estado',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='landfacility',
            name='mes_construccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landfacility',
            name='metro_redondeado',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='landfacility',
            name='num_piso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landfacility',
            name='tip_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instalacion_tipo_material', to='master_data.mastertipomaterial'),
        ),
        migrations.AddField(
            model_name='landfacility',
            name='tip_obra_complementaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tip_instalacion', to='master_data.mastertipoobracomplementaria'),
        ),
        migrations.AddField(
            model_name='landfacility',
            name='total_metrado',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='landfacility',
            name='anio_construccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
