# Generated by Django 3.2.19 on 2023-11-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0056_auto_20231120_0816'),
        ('land_inspections', '0010_landownerinspection_cod_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landsupply',
            name='cod_contr',
            field=models.ForeignKey(blank=True, db_column='cod_contr', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suministro', to='lands.landowner'),
        ),
    ]
