# Generated by Django 3.2.19 on 2024-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0011_auto_20240912_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfacility',
            name='anio_construccion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='landfacility',
            name='mes_construccion',
            field=models.IntegerField(null=True),
        ),
    ]
