# Generated by Django 3.2.19 on 2023-11-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0011_alter_landsupply_cod_contr'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordownership',
            name='ubigeo',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
