# Generated by Django 3.2.19 on 2023-11-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0012_recordownership_ubigeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinspectiontype',
            name='cod_tipo_predio',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
