# Generated by Django 3.2.19 on 2024-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0013_alter_landinspectiontype_cod_tipo_predio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordownership',
            name='file_notificacion',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='landownerinspection',
            name='cod_contr',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landownerinspection',
            name='dir_fiscal',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
