# Generated by Django 3.2.19 on 2024-01-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0014_auto_20240112_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landownerinspection',
            name='cod_contr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landownerinspection',
            name='dir_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
