# Generated by Django 3.2.19 on 2024-01-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0015_auto_20240112_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordownership',
            name='file_notificacion',
        ),
    ]
