# Generated by Django 3.2.18 on 2023-05-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Reasignar ubicación'), (2, 'Acumulación'), (3, 'División'), (4, 'Eliminar')], db_column='tipo', null=True),
        ),
    ]
