# Generated by Django 3.2.18 on 2023-05-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_application_id_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AplicationType',
        ),
    ]
