# Generated by Django 3.2.18 on 2023-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_delete_aplicationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationobservationdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
