# Generated by Django 3.2.19 on 2023-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_result_cpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Reasignar ubicación'), (2, 'Acumulación'), (3, 'División'), (4, 'Inactivar'), (5, 'Independización')], db_column='tipo', null=True),
        ),
    ]
