# Generated by Django 3.2.19 on 2024-05-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_application_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlanddetail',
            name='application',
            field=models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='maintenance.application'),
        ),
        migrations.AlterField(
            model_name='applicationresultdetail',
            name='application',
            field=models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='maintenance.application'),
        ),
    ]
