version: "3"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../catastro_fiscal/.env
    environment:
      - ENVIRONMENT=local
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  redis-data:
