# Generated by Django 3.2.19 on 2023-10-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes_data', '0002_alicuota_amnistiacontribuyente_amnistiamunicipal_baseimponible_deuda_emision_prediocaracteristica_re'),
    ]

    operations = [
        migrations.AddField(
            model_name='emision',
            name='emision_ip_corriente',
            field=models.FloatField(blank=True, help_text='Emisión de Impuesto predial del año corriente', null=True),
        ),
        migrations.AddField(
            model_name='emision',
            name='emision_ord_pago_nc',
            field=models.FloatField(blank=True, help_text='Emisión de órdenes de pago deuda no corriente predial', null=True),
        ),
    ]
