# Generated by Django 3.1.14 on 2022-08-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCodeStreet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='key id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
            ],
            options={
                'db_table': 'M_COD_VIA',
            },
        ),
        migrations.CreateModel(
            name='MasterPropertyType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='key id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
            ],
            options={
                'db_table': 'M_TIPO_PREDIO',
            },
        ),
        migrations.CreateModel(
            name='MasterSide',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='key id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
            ],
            options={
                'db_table': 'M_LADO',
            },
        ),
        migrations.CreateModel(
            name='MasterTypeUrbanUnit',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='key id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
            ],
            options={
                'db_table': 'M_TIPO_UU',
            },
        ),
    ]
