# Generated by Django 3.2.16 on 2022-11-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_auto_20220817_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'institution', 'verbose_name_plural': 'institutions'},
        ),
        migrations.AlterModelOptions(
            name='mastercodestreet',
            options={'verbose_name': 'street code', 'verbose_name_plural': 'street codes'},
        ),
        migrations.AlterModelOptions(
            name='masterpropertytype',
            options={'verbose_name': 'property type', 'verbose_name_plural': 'property types'},
        ),
        migrations.AlterModelOptions(
            name='masterresolutiontype',
            options={'verbose_name': 'resolution type', 'verbose_name_plural': 'resolution types'},
        ),
        migrations.AlterModelOptions(
            name='masterside',
            options={'verbose_name': 'side', 'verbose_name_plural': 'sides'},
        ),
        migrations.AlterModelOptions(
            name='mastertypeurbanunit',
            options={'verbose_name': 'urban unit type', 'verbose_name_plural': 'urban unit types'},
        ),
    ]
