# Generated by Django 3.2.19 on 2024-05-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_auto_20221127_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTipoContribuyente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'tipo de contribuyente',
                'verbose_name_plural': 'tipos de contribuyente',
                'db_table': 'M_TIPO_CONTRIBUYENTE',
            },
        ),
        migrations.CreateModel(
            name='MasterTipoDocumentoIdentidad',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='key id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'resolution type',
                'verbose_name_plural': 'resolution types',
                'db_table': 'M_TDOC_IDENTIDAD',
            },
        ),
        migrations.CreateModel(
            name='MasterTipoPropiedad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'tipo de propiedad',
                'verbose_name_plural': 'tipos de propiedad',
                'db_table': 'M_TIPO_PROPIEDAD',
            },
        ),
        migrations.CreateModel(
            name='MasterTipoTransferencia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'tipo de transferencia',
                'verbose_name_plural': 'tipos de transferencia',
                'db_table': 'M_TIPO_TRANSFERENCIA',
            },
        ),
        migrations.CreateModel(
            name='MasterTipoUsoPredio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'tipo uso de predio',
                'verbose_name_plural': 'tipo uso de predio',
                'db_table': 'M_TIPO_USO_PREDIO',
            },
        ),
        migrations.AddField(
            model_name='mastercodestreet',
            name='estado',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='masterpropertytype',
            name='estado',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='masterresolutiontype',
            name='estado',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='masterside',
            name='estado',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='mastertypeurbanunit',
            name='estado',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
