# Generated by Django 3.2.19 on 2024-05-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_auto_20240531_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertipocontribuyente',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='mastertipopropiedad',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='mastertipotransferencia',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='mastertipousopredio',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name'),
        ),
    ]
