# Generated by Django 3.2.19 on 2024-05-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_auto_20240531_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastertipodocumentoidentidad',
            options={'verbose_name': 'tipo de documento de identidad', 'verbose_name_plural': 'tipos de documento de identidad'},
        ),
    ]
