# Generated by Django 3.2.19 on 2024-06-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_alter_mastertipodocumentoidentidad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTipoEstadoConservacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'tipo de estado de conservacion',
                'verbose_name_plural': 'tipo de estado de conservacion',
                'db_table': 'M_TIPO_ESTADO_CONSERVACION',
            },
        ),
        migrations.CreateModel(
            name='MasterTipoMaterial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'tipo de material',
                'verbose_name_plural': 'tipo de material',
                'db_table': 'M_TIPO_MATERIAL',
            },
        ),
        migrations.CreateModel(
            name='MasterTipoNivel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'tipo de nivel',
                'verbose_name_plural': 'tipo de nivel',
                'db_table': 'M_TIPO_NIVEL',
            },
        ),
        migrations.AlterModelOptions(
            name='masterpropertytype',
            options={'verbose_name': 'tipo de predio', 'verbose_name_plural': 'tipos de predio'},
        ),
    ]
