# Generated by Django 3.2.19 on 2024-06-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_auto_20240614_0328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastertipoestadoconservacion',
            options={'verbose_name': 'tipo de estado de conservacion', 'verbose_name_plural': 'tipos de estado de conservacion'},
        ),
        migrations.AlterModelOptions(
            name='mastertipomaterial',
            options={'verbose_name': 'tipo de material', 'verbose_name_plural': 'tipos de material'},
        ),
        migrations.AlterModelOptions(
            name='mastertiponivel',
            options={'verbose_name': 'tipo de nivel', 'verbose_name_plural': 'tipos de nivel'},
        ),
        migrations.AlterModelOptions(
            name='mastertipousopredio',
            options={'verbose_name': 'tipo uso de predio', 'verbose_name_plural': 'tipos uso de predio'},
        ),
    ]
