# Generated by Django 3.2.19 on 2024-06-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_district_sec_ejec'),
        ('master_data', '0009_auto_20240614_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterresolutiontype',
            name='estado_mantenimiento',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='masterresolutiontype',
            name='estado_registro',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='masterresolutiontype',
            name='tipo',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='ResolutionTypeDistrito',
            fields=[
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
                ('resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolucion', to='master_data.masterresolutiontype')),
                ('ubigeo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='distrito', to='places.district')),
            ],
            options={
                'verbose_name': 'tipo de resolucion distrito',
                'verbose_name_plural': 'tipos de resolucion distrito',
                'db_table': 'TDOC_RES_DISTRITO',
            },
        ),
    ]
