# Generated by Django 3.2.19 on 2024-06-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_auto_20240627_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolutiontypedistrito',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resolutiontypedistrito',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resolutiontypedistrito',
            name='short_name',
        ),
    ]
