# Generated by Django 3.2.19 on 2024-08-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_auto_20240730_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClaseUso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'clase de uso',
                'verbose_name_plural': 'clases de uso',
                'db_table': 'M_CLASE_USO',
            },
        ),
        migrations.CreateModel(
            name='MasterSubClaseUso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'subclase de uso',
                'verbose_name_plural': 'subclases de uso',
                'db_table': 'M_SUBCLASE_USO',
            },
        ),
        migrations.AddField(
            model_name='mastertipousopredio',
            name='codigo_tipo_uso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastertipousopredio',
            name='codigo_clase_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.masterclaseuso'),
        ),
        migrations.AddField(
            model_name='mastertipousopredio',
            name='codigo_subclase_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.mastersubclaseuso'),
        ),
    ]
