# Generated by Django 3.2.19 on 2024-08-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_auto_20240801_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertipousopredio',
            name='codigo_clase_uso',
        ),
        migrations.AddField(
            model_name='mastersubclaseuso',
            name='codigo_clase_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.masterclaseuso'),
        ),
    ]
