# Generated by Django 3.2.19 on 2024-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_auto_20240805_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterEstadoConserva',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='key id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'estado conserva',
                'verbose_name_plural': 'estados conserva',
                'db_table': 'M_ESTADO_CONSERVA',
            },
        ),
        migrations.CreateModel(
            name='MaterMaterial',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='key id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'db_table': 'M_MATERIAL',
            },
        ),
    ]
