# Generated by Django 3.2.19 on 2024-08-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_auto_20240827_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterEstadoConserva',
        ),
        migrations.DeleteModel(
            name='MasterMaterial',
        ),
    ]
