# Generated by Django 3.2.19 on 2024-08-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_inspections', '0005_alter_location_cod_ubicacion'),
        ('master_data', '0017_auto_20240827_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterPropertyType',
            new_name='MasterTipoPredio',
        ),
    ]
