# Generated by Django 3.2.19 on 2024-09-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_rename_masterpropertytype_mastertipopredio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTipoObraComplementaria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('short_name', models.CharField(max_length=100, verbose_name='short name')),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'tipo de obra',
                'verbose_name_plural': 'tipos de obra',
                'db_table': 'M_TIPO_OBRA_COMPLEMENTARIA',
            },
        ),
    ]
