# Generated by Django 3.1.14 on 2022-02-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'ROL',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='places.department', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='places.district', verbose_name='district'),
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=8, null=True, verbose_name='dni'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='master_data.institution', verbose_name='institution'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='job_title'),
        ),
        migrations.AddField(
            model_name='user',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observation'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='places.province', verbose_name='province'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='role'),
        ),
    ]
