# Generated by Django 3.1.14 on 2022-02-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0002_auto_20220201_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
            ],
            options={
                'db_table': 'PERMISO',
            },
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='code')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
            ],
            options={
                'db_table': 'TIPO_PERMISO',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='record creation date', verbose_name='creation date')),
                ('created_by', models.CharField(blank=True, help_text='username that created the record', max_length=100, null=True, verbose_name='username created')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='record update date', verbose_name='update date')),
                ('update_by', models.CharField(blank=True, help_text='username that updated the record', max_length=100, null=True, verbose_name='username updated')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.permission', verbose_name='permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='role')),
            ],
            options={
                'db_table': 'ROL_PERMISO',
            },
        ),
        migrations.CreateModel(
            name='PermissionNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='record creation date', verbose_name='creation date')),
                ('created_by', models.CharField(blank=True, help_text='username that created the record', max_length=100, null=True, verbose_name='username created')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='record update date', verbose_name='update date')),
                ('update_by', models.CharField(blank=True, help_text='username that updated the record', max_length=100, null=True, verbose_name='username updated')),
                ('navigation_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='common.navigation', verbose_name='navigation view')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.permission', verbose_name='permission')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.permissiontype', verbose_name='permission type')),
            ],
            options={
                'db_table': 'PERMISO_NAVEGACION',
            },
        ),
    ]
