# Generated by Django 3.2.16 on 2022-11-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220308_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.AlterModelOptions(
            name='permissionnavigation',
            options={'verbose_name': 'navigation permission', 'verbose_name_plural': 'navigation permissions'},
        ),
        migrations.AlterModelOptions(
            name='permissiontype',
            options={'ordering': ['order'], 'verbose_name': 'permission type', 'verbose_name_plural': 'permission types'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'role permission', 'verbose_name_plural': 'role permissions'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
