# Generated by Django 3.2.19 on 2024-04-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('cod_tipo_foto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('desc_tipo_foto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Offer Photo Type',
                'verbose_name_plural': 'Offer Photo Type',
                'db_table': 'OFERTAS_INMOBILIARIAS_TIPO_FOTO',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('cod_foto', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cod_ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.ImageField(blank=True, null=True, upload_to='valorization')),
                ('cod_tipo_foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='valorization.phototype')),
            ],
            options={
                'verbose_name': 'Photo ',
                'verbose_name_plural': 'Photo ',
                'db_table': 'OFERTAS_INMOBILIARIAS_FOTO',
            },
        ),
    ]
