# Generated by Django 3.2.19 on 2024-04-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='url',
            new_name='url_foto',
        ),
    ]
