# Generated by Django 3.1.14 on 2022-05-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_upload', models.FileField(upload_to='lands/registry')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(choices=[('INITIAL', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('LOADED', 'Loaded')], default='INITIAL', max_length=20)),
                ('approved_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending approval'), ('APPRIVING', 'In approval process'), ('APPROVED', 'Approved')], default='NOT_REQUIRED', max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('total_records', models.PositiveSmallIntegerField(default=None, null=True)),
                ('total_new_records', models.PositiveSmallIntegerField(default=None, null=True)),
                ('total_error_records', models.PositiveSmallIntegerField(default=None, null=True)),
                ('total_update_records', models.PositiveSmallIntegerField(default=None, null=True)),
                ('total_land', models.PositiveSmallIntegerField(default=None, null=True)),
                ('total_land_mapping', models.PositiveSmallIntegerField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'upload history',
                'verbose_name_plural': 'upload history',
                'db_table': 'HISTORIAL_CARGA',
            },
        ),
    ]
