# Generated by Django 3.1.14 on 2022-05-13 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemploralUploadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INITIAL', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('LOADED', 'Loaded')], max_length=20)),
                ('upload_status', models.CharField(choices=[('INITIAL', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('LOADED', 'Loaded')], default='INITIAL', max_length=20)),
                ('upload_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.uploadhistory')),
            ],
            options={
                'verbose_name': 'temporal upload redord',
                'verbose_name_plural': 'temporal upload redords',
                'db_table': 'TMP_CARGA_REGISTROS',
            },
        ),
    ]
