# Generated by Django 3.1.14 on 2022-05-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_temploraluploadrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, max_length=2, null=True)),
                ('dni', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('paternal_surname', models.CharField(max_length=150)),
                ('maternal_surname', models.CharField(max_length=150)),
                ('tax_address', models.CharField(max_length=255)),
                ('numberLands', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'propietario',
                'verbose_name_plural': 'propietario',
                'db_table': 'PROPIETARIO',
            },
        ),
    ]
