# Generated by Django 3.1.14 on 2022-05-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_landowner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landowner',
            options={'verbose_name': 'land owner', 'verbose_name_plural': 'land owners'},
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cup', models.CharField(max_length=50)),
                ('cpm', models.CharField(blank=True, max_length=50, null=True)),
                ('habilitacion_name', models.CharField(blank=True, max_length=150, null=True)),
                ('steet_name', models.CharField(blank=True, max_length=150, null=True)),
                ('urban_mza', models.CharField(blank=True, max_length=50, null=True)),
                ('urban_lot_number', models.IntegerField(blank=True, null=True)),
                ('road_block_number', models.IntegerField(blank=True, null=True)),
                ('site', models.IntegerField(blank=True, null=True)),
                ('municipal_number', models.IntegerField(blank=True, null=True)),
                ('alternate_number', models.IntegerField(blank=True, null=True)),
                ('dpto_number', models.IntegerField(blank=True, null=True)),
                ('indoor', models.IntegerField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('built_area', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lands.landowner')),
            ],
            options={
                'verbose_name': 'land',
                'verbose_name_plural': 'land',
                'db_table': 'PREDIO',
            },
        ),
    ]
