# Generated by Django 3.1.14 on 2022-05-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_auto_20220513_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='maternal_surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='paternal_surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='tax_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
