# Generated by Django 3.1.14 on 2022-05-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_auto_20220513_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='urban_lot_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
