# Generated by Django 3.1.14 on 2022-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0006_auto_20220513_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landowner',
            old_name='numberLands',
            new_name='number_lands',
        ),
        migrations.AlterField(
            model_name='land',
            name='indoor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
