# Generated by Django 3.1.14 on 2022-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0010_auto_20220713_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='number_lands',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
