# Generated by Django 3.1.14 on 2022-08-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0011_auto_20220717_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='steet_name',
            new_name='street_name',
        ),
    ]
