# Generated by Django 3.1.14 on 2022-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0012_auto_20220811_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='id_cartographic_img',
            field=models.CharField(blank=True, help_text='id cartographic img', max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='id_plot',
            field=models.CharField(blank=True, help_text='id plot', max_length=25, null=True),
        ),
    ]
