# Generated by Django 3.1.14 on 2022-08-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0013_auto_20220816_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='status_img',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='id_cartographic_img',
            field=models.CharField(blank=True, help_text='id cartographic image', max_length=26, null=True),
        ),
    ]
