# Generated by Django 3.1.14 on 2022-08-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0014_auto_20220817_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='dpto_number',
        ),
        migrations.AddField(
            model_name='land',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
