# Generated by Django 3.1.14 on 2022-08-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0016_landaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landaudit',
            name='created_by',
            field=models.CharField(blank=True, help_text='username that created the record', max_length=100, null=True, verbose_name='username created'),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='type',
            field=models.CharField(blank=True, choices=[('editar', 'Editar Registro'), ('inactivar', 'Inactivar Registro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='update_by',
            field=models.CharField(blank=True, help_text='username that updated the record', max_length=100, null=True, verbose_name='username updated'),
        ),
    ]
