# Generated by Django 3.2.15 on 2022-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0017_auto_20220817_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landaudit',
            options={'verbose_name': 'land audit', 'verbose_name_plural': 'land audit'},
        ),
        migrations.AddField(
            model_name='land',
            name='id_object_img',
            field=models.IntegerField(blank=True, help_text='id object image', null=True),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='id_object_img',
            field=models.IntegerField(blank=True, help_text='id object image', null=True),
        ),
    ]
