# Generated by Django 3.2.15 on 2022-09-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0018_auto_20220823_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='source',
            field=models.CharField(blank=True, choices=[('carga_masiva', 'Carga Masiva'), ('asignar_lote', 'Asignar Lote'), ('asignar_img', 'Asignar Imagen')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='source_change',
            field=models.CharField(blank=True, choices=[('carga_masiva', 'Carga Masiva'), ('asignar_lote', 'Asignar Lote'), ('asignar_img', 'Asignar Imagen')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sin Cartografia'), (1, 'Con cartografia (Lote)'), (2, 'Con cartografia (Imagen)'), (3, 'Inactivo')], null=True),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='source',
            field=models.CharField(blank=True, choices=[('carga_masiva', 'Carga Masiva'), ('asignar_lote', 'Asignar Lote'), ('asignar_img', 'Asignar Imagen')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sin Cartografia'), (1, 'Con cartografia (Lote)'), (2, 'Con cartografia (Imagen)'), (3, 'Inactivo')], null=True),
        ),
    ]
