# Generated by Django 3.2.15 on 2022-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0019_auto_20220901_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='inactive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='inactive_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
