# Generated by Django 3.2.15 on 2022-10-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0022_auto_20220930_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='dni',
            field=models.CharField(max_length=20),
        ),
    ]
