# Generated by Django 3.2.15 on 2022-10-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0024_auto_20221013_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
