# Generated by Django 3.2.15 on 2022-10-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0026_auto_20221014_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='error_record',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='new_owner_record',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='new_record',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='update_owner_record',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='update_record',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
