# Generated by Django 3.2.15 on 2022-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0027_auto_20221014_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temploraluploadrecord',
            name='new_owner_record',
        ),
        migrations.RemoveField(
            model_name='temploraluploadrecord',
            name='new_record',
        ),
        migrations.RemoveField(
            model_name='temploraluploadrecord',
            name='update_owner_record',
        ),
        migrations.RemoveField(
            model_name='temploraluploadrecord',
            name='update_record',
        ),
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='land_record',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='land_record_status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='owner_record',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='owner_record_status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
