# Generated by Django 3.2.15 on 2022-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0028_auto_20221014_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='error_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
