# Generated by Django 3.2.15 on 2022-10-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0029_temploraluploadrecord_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='cup',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='cup',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
