# Generated by Django 3.2.15 on 2022-11-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0031_auto_20221109_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temploraluploadrecord',
            name='status',
            field=models.CharField(choices=[('ERROR', 'contains errors'), ('OK_NEW', 'ok and new'), ('OK_OLD', 'ok to update')], max_length=20),
        ),
    ]
