# Generated by Django 3.2.15 on 2022-11-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0032_alter_temploraluploadrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temploraluploadrecord',
            name='upload_status',
            field=models.CharField(choices=[('INITIAL', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('LOADED', 'Loaded'), ('ERROR', 'Error Loaded'), ('CANCEL', 'Cancel by user')], default='INITIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('LOADED', 'Loaded'), ('ERROR', 'Error Loaded'), ('CANCEL', 'Cancel by user')], default='INITIAL', max_length=20),
        ),
    ]
