# Generated by Django 3.2.15 on 2022-11-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_district_zone'),
        ('lands', '0033_auto_20221111_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='ubigeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.district'),
        ),
    ]
