# Generated by Django 3.2.16 on 2022-11-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0035_auto_20221126_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={'verbose_name': 'land', 'verbose_name_plural': 'lands'},
        ),
        migrations.AlterModelOptions(
            name='landaudit',
            options={'verbose_name': 'land audit', 'verbose_name_plural': 'land audits'},
        ),
        migrations.AlterModelOptions(
            name='temploraluploadrecord',
            options={'verbose_name': 'temporal upload record', 'verbose_name_plural': 'temporal upload records'},
        ),
    ]
