# Generated by Django 3.2.16 on 2023-04-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20221127_0042'),
        ('lands', '0037_auto_20230417_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='ubigeo',
            field=models.ForeignKey(db_column='ubigeo', default=150101, on_delete=django.db.models.deletion.CASCADE, to='places.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='land',
            name='cpm',
            field=models.CharField(db_column='cod_pre', default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='land',
            name='ubigeo',
            field=models.ForeignKey(db_column='ubigeo', default='150101', on_delete=django.db.models.deletion.CASCADE, to='places.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='cpm',
            field=models.CharField(db_column='cod_pre', default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='ubigeo',
            field=models.ForeignKey(db_column='ubigeo', default='150101', on_delete=django.db.models.deletion.CASCADE, to='places.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landowner',
            name='code',
            field=models.CharField(db_column='cod_contr', default='0000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landowner',
            name='document_type',
            field=models.CharField(db_column='tip_doc', default='08', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='land',
            unique_together={('ubigeo', 'cpm')},
        ),
        migrations.AlterUniqueTogether(
            name='landowner',
            unique_together={('ubigeo', 'code')},
        ),
    ]
