# Generated by Django 3.2.16 on 2023-05-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0040_alter_uploadhistory_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='source',
            field=models.CharField(blank=True, choices=[('carga_masiva', 'Carga Masiva'), ('asignar_lote', 'Asignar Lote'), ('asignar_img', 'Asignar Imagen'), ('mantenimiento_pre', 'Mantenimiento de Predio')], db_column='origen', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='source',
            field=models.CharField(blank=True, choices=[('carga_masiva', 'Carga Masiva'), ('asignar_lote', 'Asignar Lote'), ('asignar_img', 'Asignar Imagen'), ('mantenimiento_pre', 'Mantenimiento de Predio')], db_column='origen', max_length=50, null=True),
        ),
    ]
