# Generated by Django 3.2.19 on 2023-05-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0042_alter_uploadhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initiated'), ('IN_PROGRESS_TMP', 'In Progress Temporal'), ('LOADED_TMP', 'Loaded Temporal'), ('IN_PROGRESS', 'In Progress'), ('LOADED', 'Loaded'), ('ERROR', 'Error Loaded'), ('CANCEL', 'Cancel by user'), ('LOADED_START', 'Carga Inicial')], default='INITIAL', max_length=20),
        ),
    ]
