# Generated by Django 3.2.19 on 2023-05-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0043_alter_uploadhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='approved_status',
        ),
    ]
