# Generated by Django 3.2.19 on 2023-06-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0045_uploadhistory_type_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='error_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
