# Generated by Django 3.2.19 on 2023-08-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_auto_20221127_0042'),
        ('lands', '0046_temploraluploadrecord_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='status_gap_analisys',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Faltante'), (1, 'Ubicado con predio'), (2, 'Ubicado con punto campo'), (3, 'Observado')], db_column='estado_analisis_brecha', default=0, null=True),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='status_gap_analisys',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Faltante'), (1, 'Ubicado con predio'), (2, 'Ubicado con punto campo'), (3, 'Observado')], db_column='estado_analisis_brecha', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='street_type',
            field=models.ForeignKey(blank=True, db_column='tip_via', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.mastercodestreet'),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='street_type',
            field=models.ForeignKey(blank=True, db_column='tip_via', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.mastercodestreet'),
        ),
    ]
