# Generated by Django 3.2.19 on 2023-09-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0050_alter_uploadhistory_type_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='cpm',
            field=models.CharField(db_column='cod_pre', max_length=100),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='cpm',
            field=models.CharField(db_column='cod_pre', max_length=100),
        ),
    ]
