# Generated by Django 3.2.19 on 2023-10-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0051_auto_20230909_2303'),
        ('lands', '0051_auto_20230919_0808'),
    ]

    operations = [
    ]
