# Generated by Django 3.2.19 on 2023-10-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0052_merge_0051_auto_20230909_2303_0051_auto_20230919_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='temploraluploadrecord',
            name='order_record',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='cpm',
            field=models.CharField(db_column='cod_pre', max_length=50),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='cpm',
            field=models.CharField(db_column='cod_pre', max_length=50),
        ),
    ]
