# Generated by Django 3.2.19 on 2024-02-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0053_auto_20231006_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sin Cartografia'), (1, 'Con cartografia (Lote)'), (2, 'Con cartografia (Imagen)'), (3, 'Inactivo'), (4, 'Subvaluado'), (5, 'Generado en gestion de resultados')], db_column='estado', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sin Cartografia'), (1, 'Con cartografia (Lote)'), (2, 'Con cartografia (Imagen)'), (3, 'Inactivo'), (4, 'Subvaluado'), (5, 'Generado en gestion de resultados')], db_column='estado', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='landownerdetail',
            name='land',
            field=models.ForeignKey(db_column='id_predio', on_delete=django.db.models.deletion.CASCADE, related_name='predio_contribuyente', to='lands.land'),
        ),
        migrations.AlterField(
            model_name='landownerdetail',
            name='owner',
            field=models.ForeignKey(db_column='id_propietario', on_delete=django.db.models.deletion.CASCADE, related_name='contribuyentes', to='lands.landowner'),
        ),
    ]
