# Generated by Django 3.2.19 on 2023-11-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0047_auto_20230829_1144'),
        ('lands', '0053_auto_20231006_0952'),
    ]

    operations = [
    ]
