# Generated by Django 3.2.19 on 2023-11-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0054_merge_0047_auto_20230829_1144_0053_auto_20231006_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landownerdetail',
            name='land',
            field=models.ForeignKey(db_column='id_predio', on_delete=django.db.models.deletion.CASCADE, related_name='predio_contribuyente', to='lands.land'),
        ),
        migrations.AlterField(
            model_name='landownerdetail',
            name='owner',
            field=models.ForeignKey(db_column='id_propietario', on_delete=django.db.models.deletion.CASCADE, related_name='contribuyentes', to='lands.landowner'),
        ),
    ]
