# Generated by Django 3.2.19 on 2024-04-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0055_auto_20240321_1345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='land',
            unique_together=set(),
        ),
    ]
