# Generated by Django 3.2.19 on 2023-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0055_auto_20231114_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sin Cartografia'), (1, 'Con cartografia (Lote)'), (2, 'Con cartografia (Imagen)'), (3, 'Inactivo'), (4, 'Subvaluado')], db_column='estado', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sin Cartografia'), (1, 'Con cartografia (Lote)'), (2, 'Con cartografia (Imagen)'), (3, 'Inactivo'), (4, 'Subvaluado')], db_column='estado', default=0, null=True),
        ),
    ]
