# Generated by Django 3.2.19 on 2024-04-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0056_alter_land_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='cpm',
            field=models.CharField(blank=True, db_column='cod_pre', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='cpm',
            field=models.CharField(blank=True, db_column='cod_pre', max_length=50, null=True),
        ),
    ]
