# Generated by Django 3.2.19 on 2024-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0057_auto_20240410_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='landownerdetail',
            name='estado',
            field=models.IntegerField(blank=True, db_column='estado', null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='fecha_registro',
            field=models.DateField(blank=True, db_column='fecha_registro', null=True),
        ),
    ]
