# Generated by Django 3.2.19 on 2024-04-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0058_auto_20240425_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landownerdetail',
            old_name='fecha_registro',
            new_name='date_register',
        ),
        migrations.RenameField(
            model_name='landownerdetail',
            old_name='estado',
            new_name='status',
        ),
    ]
