# Generated by Django 3.2.19 on 2024-05-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0059_auto_20240425_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedioContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'tipo de medio de contacto',
                'verbose_name_plural': 'tipo de medios de contactos',
                'db_table': 'TIPO_MEDIO_CONTACTO',
            },
        ),
        migrations.RenameField(
            model_name='landownerdetail',
            old_name='status',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='landownerdetail',
            old_name='date_register',
            new_name='fecha_registro',
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubigeo', models.CharField(blank=True, max_length=10, null=True)),
                ('des_domicilio', models.CharField(blank=True, max_length=500, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=6, null=True)),
                ('indoor', models.CharField(blank=True, max_length=5, null=True)),
                ('piso', models.CharField(blank=True, max_length=2, null=True)),
                ('kilometro', models.CharField(blank=True, max_length=4, null=True)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('contribuyente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='domicilio', to='lands.landowner')),
            ],
            options={
                'verbose_name': 'direccion',
                'verbose_name_plural': 'direcciones',
                'db_table': 'DOMICILIO',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('principal', models.IntegerField(blank=True, null=True)),
                ('contribuyente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacto', to='lands.landowner')),
                ('tipo_med_contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lands.tipomediocontacto')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'db_table': 'CONTACTO',
            },
        ),
    ]
