# Generated by Django 3.2.19 on 2024-05-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0060_auto_20240516_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilio',
            old_name='indoor',
            new_name='puerta',
        ),
    ]
