# Generated by Django 3.2.19 on 2024-05-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_auto_20240531_1146'),
        ('places', '0006_auto_20221127_0042'),
        ('lands', '0061_rename_indoor_domicilio_puerta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='block',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='kilometro',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='puerta',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='landowner',
            name='tax_address',
        ),
        migrations.RemoveField(
            model_name='landownerdetail',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='land',
            name='id_lote_puerta',
            field=models.CharField(blank=True, db_column='id_lote_puerta', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='latitude_puerta',
            field=models.FloatField(blank=True, db_column='coor_y_puerta', null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='longitude_puerta',
            field=models.FloatField(blank=True, db_column='coor_x_puerta', null=True),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='id_lote_puerta',
            field=models.CharField(blank=True, db_column='id_lote_puerta', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='latitude_puerta',
            field=models.FloatField(blank=True, db_column='coor_y_puerta', null=True),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='longitude_puerta',
            field=models.FloatField(blank=True, db_column='coor_x_puerta', null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='area_construida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='area_terreno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='area_tot_cons_comun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='area_tot_terr_comun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='cantidad_habitantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='cpm',
            field=models.CharField(blank=True, db_column='cod_cpm', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='cup',
            field=models.CharField(blank=True, db_column='cod_cpu', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='fec_transferencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='fecha_dj',
            field=models.DateField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='longitud_frente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='numero_dj',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='par_registral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='por_propiedad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='pre_inhabitable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='tip_propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.mastertipopropiedad'),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='tip_transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.mastertipotransferencia'),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='tip_uso_predio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.mastertipousopredio'),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='document_type',
            field=models.ForeignKey(blank=True, db_column='tip_doc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.mastertipodocumentoidentidad'),
        ),
        migrations.AlterField(
            model_name='landownerdetail',
            name='estado',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='landownerdetail',
            name='ubigeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.district'),
        ),
    ]
