# Generated by Django 3.2.19 on 2024-05-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_auto_20240531_1158'),
        ('lands', '0062_auto_20240531_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='tipo_contribuyente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.mastertipocontribuyente'),
        ),
    ]
