# Generated by Django 3.2.19 on 2024-06-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0064_auto_20240603_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='id_lot_polig',
            field=models.CharField(blank=True, db_column='id_lot_polig', help_text='id plot', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='id_lot_polig',
            field=models.CharField(blank=True, db_column='id_lot_polig', help_text='id plot', max_length=25, null=True),
        ),
    ]
