# Generated by Django 3.2.19 on 2024-06-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0065_auto_20240610_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='id_lot_polig',
        ),
        migrations.RemoveField(
            model_name='landaudit',
            name='id_lot_polig',
        ),
        migrations.AddField(
            model_name='land',
            name='id_lote_p',
            field=models.CharField(blank=True, db_column='id_lote_p', help_text='id plot', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='id_lote_p',
            field=models.CharField(blank=True, db_column='id_lote_p', help_text='id plot', max_length=25, null=True),
        ),
    ]
