# Generated by Django 3.2.19 on 2024-06-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0067_auto_20240610_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='id_lote_p',
            field=models.IntegerField(blank=True, db_column='id_lote_p', help_text='id lot poligono', null=True),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='id_lote_p',
            field=models.IntegerField(blank=True, db_column='id_lote_p', help_text='id lot poligono', null=True),
        ),
    ]
