# Generated by Django 3.2.19 on 2024-06-14 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_auto_20240614_0328'),
        ('places', '0006_auto_20221127_0042'),
        ('lands', '0068_auto_20240610_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landownerdetail',
            name='fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='OwnerDeuda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiene_deuda', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('land_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lands.landowner')),
            ],
            options={
                'verbose_name': 'nivel de construccion',
                'verbose_name_plural': 'niveles de construccion',
                'db_table': 'PROPIETARIO_DEUDA',
            },
        ),
        migrations.CreateModel(
            name='LandNivelConstruccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_piso', models.IntegerField(blank=True, null=True)),
                ('anio_construccion', models.IntegerField(blank=True, null=True)),
                ('mes_construccion', models.IntegerField(blank=True, null=True)),
                ('area_construida', models.FloatField(blank=True, null=True)),
                ('area_construida_comun', models.FloatField(blank=True, null=True)),
                ('por_area_construida_comun', models.FloatField(blank=True, null=True)),
                ('categoria_muro_columna', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria_puerta_ventana', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria_revestimiento', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria_bano', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria_inst_electrica_sanita', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('est_conservacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_estado_conservacion', to='master_data.mastertipoestadoconservacion')),
                ('land_owner_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_land_owner_detail', to='lands.landownerdetail')),
                ('tip_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_tipo_material', to='master_data.mastertipomaterial')),
                ('tip_nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_tipo_nivel', to='master_data.mastertipomaterial')),
                ('ubigeo', models.ForeignKey(db_column='ubigeo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_ubigeo', to='places.district')),
            ],
            options={
                'verbose_name': 'nivel de construccion',
                'verbose_name_plural': 'niveles de construccion',
                'db_table': 'PREDIO_NIVEL_CONSTRUCCION',
            },
        ),
    ]
