# Generated by Django 3.2.19 on 2024-06-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_auto_20240614_1011'),
        ('lands', '0069_auto_20240614_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerdeuda',
            old_name='land_owner',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='landnivelconstruccion',
            name='tip_nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_tipo_nivel', to='master_data.mastertiponivel'),
        ),
        migrations.AlterField(
            model_name='landownerdetail',
            name='fecha_dj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landownerdetail',
            name='numero_dj',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='landownerdetail',
            name='par_registral',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
