# Generated by Django 3.2.19 on 2024-06-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0070_auto_20240614_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='landownerdetail',
            name='code',
            field=models.CharField(blank=True, db_column='cod_contr', max_length=50, null=True),
        ),
    ]
