# Generated by Django 3.2.19 on 2024-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0071_landownerdetail_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='landownerdetail',
            name='anio_determinacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownerdetail',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
