# Generated by Django 3.2.19 on 2024-06-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0073_auto_20240624_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilio',
            old_name='ubigeo',
            new_name='ubigeo_domicilio',
        ),
        migrations.AlterUniqueTogether(
            name='landowner',
            unique_together=set(),
        ),
    ]
