# Generated by Django 3.2.19 on 2024-07-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0074_auto_20240624_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='sec_ejec',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
