# Generated by Django 3.2.19 on 2024-07-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0075_landowner_sec_ejec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
