# Generated by Django 3.2.19 on 2024-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0076_rename_decripcion_contacto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='landownerdetail',
            name='predial_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
