# Generated by Django 3.2.19 on 2024-07-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0077_landownerdetail_predial_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='tipo_med_contacto',
            new_name='tip_med_contacto',
        ),
    ]
