# Generated by Django 3.2.19 on 2024-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0079_auto_20240730_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='landnivelconstruccion',
            name='categoria_piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='landnivelconstruccion',
            name='categoria_techo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
