# Generated by Django 3.2.19 on 2024-09-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_rename_masterpropertytype_mastertipopredio'),
        ('lands', '0080_auto_20240827_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='landaudit',
            name='property_type',
        ),
        migrations.AddField(
            model_name='land',
            name='cod_tipo_predio',
            field=models.ForeignKey(blank=True, db_column='cod_tipo_predio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.mastertipopredio'),
        ),
        migrations.AddField(
            model_name='landaudit',
            name='cod_tipo_predio',
            field=models.ForeignKey(blank=True, db_column='cod_tipo_predio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.mastertipopredio'),
        ),
    ]
