# Generated by Django 3.2.19 on 2024-09-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_rename_masterpropertytype_mastertipopredio'),
        ('lands', '0081_auto_20240905_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='cod_tipo_predio',
            field=models.ForeignKey(blank=True, db_column='cod_tipo_predio', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.mastertipopredio'),
        ),
        migrations.AlterField(
            model_name='landaudit',
            name='cod_tipo_predio',
            field=models.ForeignKey(blank=True, db_column='cod_tipo_predio', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.mastertipopredio'),
        ),
    ]
