# Generated by Django 3.2.19 on 2024-09-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_district_sec_ejec'),
        ('master_data', '0019_mastertipoobracomplementaria'),
        ('lands', '0082_auto_20240906_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrComConstruccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_piso', models.IntegerField(blank=True, null=True)),
                ('anio_construccion', models.IntegerField(blank=True, null=True)),
                ('mes_construccion', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('metreo_redondeado', models.FloatField(null=True)),
                ('total_metreado', models.FloatField(null=True)),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
                ('est_conservacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='obr_estado_conservacion', to='master_data.mastertipoestadoconservacion')),
                ('land_owner_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='obr_construccion', to='lands.landownerdetail')),
                ('tip_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='obr_tipo_material', to='master_data.mastertipomaterial')),
                ('tip_obra_complementaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='obr_tipo_material', to='master_data.mastertipoobracomplementaria')),
                ('ubigeo', models.ForeignKey(db_column='ubigeo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='obr_ubigeo', to='places.district')),
            ],
            options={
                'verbose_name': 'obra construccion',
                'verbose_name_plural': 'obras construccion',
                'db_table': 'OBR_COM_CONSTRUCCION',
            },
        ),
    ]
