# Generated by Django 3.2.19 on 2024-09-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0083_obrcomconstruccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obrcomconstruccion',
            old_name='metreo_redondeado',
            new_name='metro_redondeado',
        ),
        migrations.RenameField(
            model_name='obrcomconstruccion',
            old_name='total_metreado',
            new_name='total_metrado',
        ),
        migrations.AlterField(
            model_name='obrcomconstruccion',
            name='land_owner_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='obras_complementarias', to='lands.landownerdetail'),
        ),
    ]
