# Generated by Django 3.1.14 on 2022-01-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('group', 'Group'), ('collapsable', 'Collapsable'), ('basic', 'Basic')], max_length=50)),
                ('icon', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.navigation')),
            ],
            options={
                'db_table': 'MENU',
                'ordering': ['order'],
            },
        ),
    ]
