# Generated by Django 3.2.16 on 2022-11-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'ordering': ['order'], 'verbose_name': 'navigation', 'verbose_name_plural': 'navigations'},
        ),
    ]
